<a href="https://colab.research.google.com/github/sreenada/Sreenada_DSK/blob/main/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Package: Numpy

#### Refferences
https://www.pluralsight.com/guides/overview-basic-numpy-operations <br>
https://www.w3schools.com/python/numpy/

In [ ]:
#Importing packages with alias
import pandas as pd
import numpy as np

### Numpy

##### Numpy is a collection of elemnts of same data type. <br> where as its competition python list can hold elements of any data type.

In [ ]:
npary = np.array([1,2,3,4,5])
print(npary)
print(type(npary))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#creating a series of numbers lets say 1 to 15

a =np.arange(15) ## 0 to n-1, here (15-1)
b =np.arange(5,15) ## starting from 5 to 14
c =np.arange(0,15,2) ## staring form 1 to 14, with an interval of 2

print(" a=",a,"\n","b=",b,"\n","c=",c,"\n")

print(type(a))

 a= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
 b= [ 5  6  7  8  9 10 11 12 13 14] 
 c= [ 0  2  4  6  8 10 12 14] 

<class 'numpy.ndarray'>


#### Note : reshape is temporoary and resize is permenant

In [ ]:
# 'a' is 1x15 in dimension, to convert it to 3x5
print ("reshape function \n",a.reshape(3,5),"\n") ## the change is temporary
print("checking after reshape function \n",a,"\n")
a.resize(3,5)  ## the change is permenant
print("check for a after resize \n",a)

reshape function 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

checking after reshape function 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

check for a after resize 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
#Creating a multi diamentional array
np.random.randint(1,25,size=(5,4))

array([[ 3,  8, 13, 19],
       [11,  7, 15, 15],
       [14,  1, 23,  1],
       [11, 20, 24, 18],
       [13, 11, 16,  8]])

##### There are a lot of functions, all of which cannot be explanined. if done so this will become the help file. <br>  So pls be familiar with the commands and the remaining things like syntax and useage could be obtained form inbuilt help/google

Help about a pirticular function can be obtained as follows. <br>
To see list of functions avaiable on numpy. <br>
just type "numpy." or "np."(if using alias)  and press tab

#### Syntax for help

In [ ]:
# Syntax
# np.info(np.function_name)
np.info(np.random.randint)

randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

Parameters
----------
low : int
    Lowest (signed) integer to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. All dtypes are determined by their
    name, i.e., 'int64', 'int'

In [ ]:
#printing 8 values between 0 to 20
print(np.linspace(0,20,8))

[ 0.          2.85714286  5.71428571  8.57142857 11.42857143 14.28571429
 17.14285714 20.        ]


In [ ]:
print(a,"\n")
print("the shape of array a:",a.shape)
print("the dimension of array a:",a.ndim)
print("the total no of elements in array a:",a.size)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

the shape of array a: (3, 5)
the dimension of array a: 2
the total no of elements in array a: 15


In [ ]:
#array creation
aa =np.array([1,2,3,4,5])  ## Regular array
ab=np.array([[1, 2], [3, 4]]) ## Multi dimesnional array
ac=np.array([[1,2],[5,6]],dtype = complex) ## complex array

print ("Regular Array\n",aa, "\n\nMulti Dimensional Array (here 2D) \n",ab,"\n\nComplex Array\n",ac)

Regular Array
 [1 2 3 4 5] 

Multi Dimensional Array (here 2D) 
 [[1 2]
 [3 4]] 

Complex Array
 [[1.+0.j 2.+0.j]
 [5.+0.j 6.+0.j]]


#### operations in numpy array

In [ ]:
#slicing and dicing,
DSK=np.array([
[["a","b","c"],["d","e","f"]],
[["g","h","i"],["j","k","l"]]
])

print(DSK[0][0][0],"\n")
print(DSK[0][0],"\n")
print(DSK[0],"\n")

DSK2=np.array([["a","b","c","d","e","f"],["g","h","i","j","k","l"]])
DSK2[0][0:3]

#In DSK2 printing the section 1, and that too the first 3 elements only.
#Note: here n-1 is taken as the upper limit.

a 

['a' 'b' 'c'] 

[['a' 'b' 'c']
 ['d' 'e' 'f']] 



array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print("A= \n",A,"\nB=\n",B)

A= 
 [[1 1]
 [0 1]] 
B=
 [[2 0]
 [3 4]]


#### Element wise and Matrix Multiplication

In [ ]:
print(A*B,"\n")         ## Element wise multiplication
print("\n",A.dot(B))    ## Matrix Multiplication


[[2 0]
 [0 4]] 


 [[5 4]
 [3 4]]


In [ ]:
#generating and reshaping
print("15 random numbers (b/w 0 and 1), reshaped to 5 rows and 3 cols \n",np.random.random(15).reshape(5,3),"\n\n")
#or
print("15 random numbers (b/w 1 and 20), reshaped to 5 rows and 3 cols \n",np.random.randint(1,20, size=(5,3)),"\n\n")

print("15 random numbers (b/w 0 and 100) \n",np.random.randint(0,100,size=15))


15 random numbers (b/w 0 and 1), reshaped to 5 rows and 3 cols 
 [[0.66170746 0.25599191 0.89386444]
 [0.78905742 0.38012069 0.54118996]
 [0.85622064 0.5881181  0.67014658]
 [0.50889932 0.89647414 0.74708635]
 [0.74670335 0.22066635 0.91584827]] 


15 random numbers (b/w 1 and 20), reshaped to 5 rows and 3 cols 
 [[ 1 14 12]
 [ 8 12 17]
 [17 19  3]
 [18  7 14]
 [ 9 15 16]] 


15 random numbers (b/w 0 and 100) 
 [83 49 80 31 93 25 30 52 29 15 53 37 90  5 37]


In [ ]:
#other built in funtions
zz=int(input())
print("the value of ",zz,": ", zz,"\n")
print("the value of square root of ",zz,": ",np.sqrt(zz),"\n")
print("the value of ",zz,": ", np.sin(zz), "\n By default the function takes degrees in rads. \n")
print("the value of sine ",zz,":  in degrees", np.sin(np.deg2rad(zz)))

90
the value of  90 :  90 

the value of square root of  90 :  9.486832980505138 

the value of  90 :  0.8939966636005579 
 By default the function takes degrees in rads. 

the value of sine  90 :  in degrees 1.0


In [ ]:
#Converting degrees to rad
np.deg2rad(90)

1.5707963267948966

In [ ]:
var_b = np.random.randint(1,20, size=(3,3))
print(var_b)

[[ 5 13 10]
 [19  5  5]
 [ 5  8  3]]


In [ ]:
print("Sum of Columns",var_b.sum(axis=0)) ## the sum of values of columns
print("Sum of Rows",var_b.sum(axis=1)) ## the sum of values of Row
print("Max value",var_b.max())
print("Total sum",var_b.sum())
print("Minimum value",var_b.min())
print("Mean value",var_b.mean())
print("Standard deviation",var_b.std())

Sum of Columns [29 26 18]
Sum of Rows [28 29 16]
Max value 19
Total sum 73
Minimum value 3
Mean value 8.11111111111111
Standard deviation 4.840671313509325


In [ ]:
#converting a multi dimensional array to a single dimensional array
print("var_b=\n",var_b)
var_c = var_b.ravel()
print("var_c = ",var_c)

var_b=
 [[ 5 13 10]
 [19  5  5]
 [ 5  8  3]]
var_c =  [ 5 13 10 19  5  5  5  8  3]


In [ ]:
var_d = np.resize(var_c,(5,2))
print(var_d)
#note : here var_c had only 9 elements. when we reshared it to 5x2 it required 10 elements,
# in this case it reuse or loop through the elements of the source

[[ 5 13]
 [10 19]
 [ 5  5]
 [ 5  8]
 [ 3  5]]


In [ ]:
#one more example
var_e = np.resize(var_c,(4,3))
print(var_e)
#it is seen that the first row is repeated again

[[ 5 13 10]
 [19  5  5]
 [ 5  8  3]
 [ 5 13 10]]


Stacking array together
vstack -> vertical stack
hstack -> horizontal stack


In [ ]:
stk_a =np.arange(1,5).reshape(2,2)
stk_b= np.arange(4,8).reshape(2,2)

print("stk_a=\n",stk_a,"\nstk_b=\n",stk_b)

stk_a=
 [[1 2]
 [3 4]] 
stk_b=
 [[4 5]
 [6 7]]


In [ ]:
stk_vs=np.vstack((stk_a,stk_b))
print(stk_vs)
print("\n")
stk_hs=np.hstack((stk_a,stk_b))
print(stk_hs)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


[[1 2 4 5]
 [3 4 6 7]]


In [ ]:
#Shallow copy and deep copy
shallow_a = np.arange(1,15)
print("shallow_a",shallow_a)
shallow_b = shallow_a
print("shallow_b", shallow_b)

print("updating value of 5th element of shallow_b to 99\n")
shallow_b[4]=99

print("shallow_b", shallow_b, "\nThe change was expected\n")

print("shallow_a",shallow_a,"\nThe change was un-expected\n")

print("inshort a=b kind of assignment is similar to an alias and technically they are the same.")
print("this kind of copy is called shallow copy")

shallow_a [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
shallow_b [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
updating value of 5th element of shallow_b to 99

shallow_b [ 1  2  3  4 99  6  7  8  9 10 11 12 13 14] 
The change was expected

shallow_a [ 1  2  3  4 99  6  7  8  9 10 11 12 13 14] 
The change was un-expected

inshort a=b kind of assignment is similar to an alias and technically they are the same.
this kind of copy is called shallow copy


In [ ]:
#Deep Copy
deep_a = np.arange(1,15)
print("deep_a",deep_a,"\n")
deep_b = deep_a.copy()
print("deep_b",deep_b,"\n")

print("updating value of 5th element of deep_b to 99\n")
deep_b[4]=99

print("deep_b", deep_b, "\nThe change was expected\n")

print("deep_a",deep_a,"\n no change, as expected\n")

deep_a [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

deep_b [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

updating value of 5th element of deep_b to 99

deep_b [ 1  2  3  4 99  6  7  8  9 10 11 12 13 14] 
The change was expected

deep_a [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
 no change, as expected



#### Why Numpy over python list?

##### 1) The numpy list is smaller in size thus faster!

In [ ]:
import sys
import time

In [ ]:
#Python list
pyt_lst =list(range(1,151))  ### creating a list with elemetns from 1 to 150
print("\npython list size :",sys.getsizeof(pyt_lst))


python list size : 1456


In [ ]:
#Numpy list
npy_lst =np.arange(1,151,1) ### creating a list with elemetns from 1 to 150
print("\nnumpy list size:",sys.getsizeof(npy_lst))


numpy list size: 696


##### 2) Simpler calculations

In [ ]:
height = [1.72,1.65,1.66,1.78,1.9]
weight = [75,54,62,74,80]

In [ ]:
# BMI = height in Weight/(height^2(in meters))
#
#weight/height**2  ==> this code will fail
#
for i in range (0,len(height),1) :
    print(weight[i]/height[i]**2)

25.351541373715524
19.834710743801654
22.49963710262738
23.355636914530994
22.1606648199446


In [ ]:
npy_height = np.array(height)
npy_weight = np.array(weight)

print(npy_weight/(npy_height**2))

[25.35154137 19.83471074 22.4996371  23.35563691 22.16066482]


##### Here you could skip all those looping statemetns just by using numpy lists

#### Array Join

In [ ]:
arr1 = np.array([1, 2, 3]) #array 1
arr2 = np.array([4, 5, 6]) #array 2
ary = np.concatenate((arr1, arr2))
print(ary)

[1 2 3 4 5 6]


In [ ]:
Mar1 = np.array([[1, 2], [3, 4]])

Mar2 = np.array([[5, 6], [7, 8]])

M_array1 = np.concatenate((Mar1, Mar2), axis=1)

print("axis 1 is horizontal")
print(M_array1, "\n")


M_array2 = np.concatenate((Mar1, Mar2), axis=0)
print("axis 0 is vertical")
print(M_array2)

axis 1 is horizontal
[[1 2 5 6]
 [3 4 7 8]] 

axis 0 is vertical
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Array Split

In [ ]:
ary1 = np.array([1, 2, 3, 4, 5, 6])
print("the array split into 2: \n",np.array_split(ary1, 2),"\n")

print("the array split into 3: \n",np.array_split(ary1, 3))

the array split into 2: 
 [array([1, 2, 3]), array([4, 5, 6])] 

the array split into 3: 
 [array([1, 2]), array([3, 4]), array([5, 6])]


#### Array Search

In [ ]:
ar_sr = np.array([4, 2, 3, 4, 5, 4, 7, 8, 9, 7, 4])

x = np.where(ar_sr == 4)

print("the location where 4 was found: ",x)

print("Printing with the location provided form variable x : \n",ar_sr[x])

the location where 4 was found:  (array([ 0,  3,  5, 10], dtype=int64),)
Printing with the location provided form variable x : 
 [4 4 4 4]


In [ ]:
#### Array Sort
ar_so = np.array([3, 2, 99, 1,4,9,81,0,29,5,7,9,11,45,24,15,18,19])
ar_sort=np.sort(ar_so)
print("sorted order:",ar_sort,"\n")
print("descending order sort:",ar_sort[::-1])


sorted order: [ 0  1  2  3  4  5  7  9  9 11 15 18 19 24 29 45 81 99] 

descending order sort: [99 81 45 29 24 19 18 15 11  9  9  7  5  4  3  2  1  0]


In [ ]:
## descending order sort can also be perfomed as follows.
print(np.sort(ar_so)[::-1])

[99 81 45 29 24 19 18 15 11  9  9  7  5  4  3  2  1  0]


##### Some Points to remember

In [ ]:
pyt_lst2 = [1,"a",3.14,True]
npy_lst2 = np.array([1,"a",3.14,True])

In [ ]:
print("pyt_lst2 = ",pyt_lst2,"\n")
print("npy_lst2 = ",npy_lst2)

pyt_lst2 =  [1, 'a', 3.14, True] 

npy_lst2 =  ['1' 'a' '3.14' 'True']


Here python list mainitains the input data type as it is, but <br>
numpy converts all into a common data type, here all as string

In [ ]:
print("height+weight =",height+weight)
print("npy_height+npy_weight =",npy_height+npy_weight)

height+weight = [1.72, 1.65, 1.66, 1.78, 1.9, 75, 54, 62, 74, 80]
npy_height+npy_weight = [76.72 55.65 63.66 75.78 81.9 ]


Here in regular list + function results in concatenation <br>
where as in npy_lists it results in element wise addition.

In [ ]:
print ("A question , we have the following data, ")
print("height = ", height, "\n", "weight =",weight )
print("Question : how to find the weight of people of height 1.75m and above?")

A question , we have the following data, 
height =  [1.72, 1.65, 1.66, 1.78, 1.9] 
 weight = [75, 54, 62, 74, 80]
Question : how to find the weight of people of height 1.75m and above?


In [ ]:
npy_height > 1.75

array([False, False, False,  True,  True])

In [ ]:
npy_weight[npy_height>1.75]

array([74, 80])